openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
paths:
  /api/todos:
    get:
      summary: List all todos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItem'
    post:
      summary: Add a todo item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoItem'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
  /api/todos/{id}/complete:
    post:
      summary: Mark todo as completed
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '404':
          description: Not found
components:
  schemas:
    TodoItem:
      type: object
      properties:
        id:
          type: integer
        description:
          type: string
        completedDate:
          type: string
          format: date
