name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y maven
    - name: Run server tests
      run: |
        cd server
        ./run_tests.sh
    - name: Run client tests
      run: |
        cd client
        npm install
        node test.js
